name: Deploy to GCE

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: self-hosted



    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          echo "${{ secrets.GCE_SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
            cd /path/to/your/app  # e.g., /home/lakshman/myapp
            git pull origin main  # pull latest code
            # Optional: stop previous app
            # pkill -f app.py
            # Run your app (example: Flask)
            nohup python3 app.py > app.log 2>&1 &
          EOF
