name: Deploy to Google Compute Engine
run-name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/deploy.yml
      

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set environment variables
        working-directory: ./frontend
        run: |
          echo "VITE_API_BASE_URL=https://edudiagno.com/api/v1" >> .env
          echo "VITE_DSA_WS_BASE_URL=wss://edudiagno.com/api/v1/interview" >> .env
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy frontend to GCE VM
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_rsa" \
            ./frontend/dist/ ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }}:/home/${{ secrets.GCE_USER }}/frontend

      - name: Start static server via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
            # Kill existing serve process if running
            pkill -f "serve -s" || true
            # Reinstall serve if needed
            command -v serve >/dev/null 2>&1 || npm install -g serve
            # Start serve in background on port 80
            nohup serve -s /home/${{ secrets.GCE_USER }}/frontend -l 80 > serve.log 2>&1 &
          EOF
